package Audio;

import javax.sound.sampled.*;
/**
 * Class {@code AudioThread} Audio player as a thread
 *
 * <p> For playing the audio in the thread
 *
 * @author : Damon,JavaDoc edit by Weizhi
 * @since : 19/02/2020
 */
public class AudioThread extends Thread {

    public static boolean isRun = true;
    private AudioClip sfx;
    private double vol;
    private Clip clip;

    /**
     * Constructor for AudioThread
     *
     * <p> Play audio in a thread.
     *
     * @param sfx the AudioClip generated by file
     * @param vol set the volume of the sound
     * @author Damon,JavaDoc edit by Weizhi
     * @version 1.0
     */
    public AudioThread(AudioClip sfx, double vol){
        this.sfx = sfx;
        this.vol = vol;
    }

    /**
     * Stop Audio from playing
     *
     * <p> Stop playing current audio
     * @author Damon,JavaDoc edit by Weizhi
     * @version 1.0
     */
    public void stopMusic(){
        clip.stop();
    }

    /**
     * Start Playing Audio
     *
     * <p> Start playing current audio
     * @author Damon,JavaDoc edit by Weizhi
     * @version 1.0
     */
    public void startMusic(){
        clip.start();
    }

    /**
     * the basic function generated by thread
     *
     * <p> Thread.run
     * @author Damon,JavaDoc edit by Weizhi
     * @version 1.0
     */
    public void run() {
        try {
            AudioInputStream stream = sfx.getAudioStream();
            clip = AudioSystem.getClip();

            clip.open(stream);
            clip.loop(Clip.LOOP_CONTINUOUSLY);

            //We need to open the clip before we set the volume otherwise it won't work
            setVol(vol, clip);
            //Starts playing the Audio Clip
            clip.start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Set the volume of the sound
     *
     * <p> no comment
     * @param clip Clip Class generated by target audio file
     * @param vol the volume of the sound, from 0 to 1, the volume increase
     * @author Damon,JavaDoc edit by Weizhi
     * @version 1.0
     */
    private static void setVol(double vol, Clip clip) {
        FloatControl gain = (FloatControl)clip.getControl(FloatControl.Type.MASTER_GAIN);
        //Using variable "db" (Decibels)
        //even though I have a vol variable as when working with gain you it to be in decibels as float is in the scale of 0 to 1.0
        float dB = (float) (Math.log(vol) / Math.log(10) * 20);
        gain.setValue(dB);
    }
}
